Projet/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projet;

namespace Projet.Controllers
{
    public class AlbumsController : Controller
    {
        private Classique_Web_2017Entities db = new Classique_Web_2017Entities();

        // GET: Albums
        public ActionResult Index()
        {
            var album = db.Album.Include(a => a.Editeur).Include(a => a.Genre);
            return View(album.ToList());
        }
        public ActionResult Pochette(int? id)
        {
            var album = db.Album.Single(g => g.Code_Album == id);
            return File(album.Pochette, "image/jpeg");
        }

        // GET: Albums/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Album.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }

            var data = db.Musicien.Single(g => g.Code_Musicien == id);
            ViewBag.Nom = data.Nom_Musicien;
            ViewBag.Prenom = data.Prenom_Musicien;

            return View(album);
        }
        // GET: Albums/listeAlbums/5
        public ActionResult listeAlbums(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var album = (from a in db.Album
                         join gen in db.Genre on a.Code_Genre equals gen.Code_Genre
                         join mus in db.Musicien on gen.Code_Genre equals mus.Code_Genre
                         join comp in db.Composer on mus.Code_Musicien equals comp.Code_Musicien
                         where mus.Code_Musicien == id
                         select a).Distinct();
            

            var data = db.Musicien.Single(g => g.Code_Musicien == id);
            ViewBag.Nom = data.Nom_Musicien;
            ViewBag.Prenom = data.Prenom_Musicien;
            ViewBag.Code = data.Code_Musicien;

            return View(album.ToList());

        }
        // GET: Albums/listeAlbumsRecherche

        public ActionResult listeAlbumsRecherche(string alb)
        {
            if (alb == null)
                alb = "";

            var album = (from a in db.Album
                         join gen in db.Genre on a.Code_Genre equals gen.Code_Genre
                         join mus in db.Musicien on gen.Code_Genre equals mus.Code_Genre
                         join comp in db.Composer on mus.Code_Musicien equals comp.Code_Musicien
                         where a.Titre_Album.StartsWith(alb)
                         select a).Distinct();

            return View(album.ToList());

        }

        public ActionResult listeAlbumsFromOeuvres(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var album = (from oe in db.Oeuvre
                           join comp in db.Composer on oe.Code_Oeuvre equals comp.Code_Oeuvre
                           join mus in db.Musicien on comp.Code_Musicien equals mus.Code_Musicien
                           join pay in db.Pays on mus.Code_Pays equals pay.Code_Pays
                           join edi in db.Editeur on pay.Code_Pays equals edi.Code_Pays
                           join alb in db.Album on edi.Code_Editeur equals alb.Code_Editeur
                           where oe.Code_Oeuvre == id
                           select alb).Distinct();
            var data = db.Album.Single(g => g.Code_Album == id);
            ViewBag.Titre_Album = data.Titre_Album;
            ViewBag.Code = id;
            return View(album);
        }
    }

    }

Projet/Controllers/EnregistrementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projet;

namespace Projet.Controllers
{
    public class EnregistrementsController : Controller
    {
        private Classique_Web_2017Entities db = new Classique_Web_2017Entities();

        // GET: Enregistrements
        public ActionResult Index()
        {
            return View(db.Enregistrement.ToList());
        }
        public ActionResult Extrait(int? id)
        {
            var enregistrement = db.Enregistrement.Single(g => g.Code_Morceau == id);
            return File(enregistrement.Extrait, "mp3");
        }
        public ActionResult listeEnregistrementsFromAlbum(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var enregistrement = (from enr in db.Enregistrement
                                  join comp in db.Composition_Disque on enr.Code_Morceau equals comp.Code_Morceau
                                  join dis in db.Disque on comp.Code_Disque equals dis.Code_Disque
                                  join alb in db.Album on dis.Code_Album equals alb.Code_Album
                                  where alb.Code_Album == id
                                  select enr).Distinct();
            //  var data = db.Album.Single(g => g.Code_Album == id);
            // ViewBag.Titre_Album = data.Titre_Album;
            ViewBag.Code = id;
            return View(enregistrement);
        }

        public ActionResult listeEnregistrementsFromOeuvres(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var enregistrement = (from enr in db.Enregistrement
                                  join comp in db.Composition_Oeuvre on enr.Code_Composition equals comp.Code_Composition
                                  join oe in db.Oeuvre on comp.Code_Oeuvre equals oe.Code_Oeuvre
                                  where oe.Code_Oeuvre == id
                                  select enr).Distinct();
            //  var data = db.Oeuvre.Single(g => g.Code_Oeuvre == id);
            //ViewBag.Titre_Album = data.Titre_Oeuvre;
            ViewBag.Code = id;
            return View(enregistrement);
        }
        public ActionResult panier()
        {
            //if (!Request.IsAuthenticated)
            //{
            //    return RedirectToAction("Login", "Account");
            //}



            if (Session["Panier"] == null)
            {
                Session["Panier"] = new List<int>();
            }

            List<int> mylist = new List<int>((List<int>)Session["Panier"]);

            List<Enregistrement> panier = new List<Enregistrement>();

            foreach (var item in mylist)
            {
                panier.Add(db.Enregistrement.Find(item));

            }

            return View(panier);
        }
        [Route("ajoutPanier/{id,code,fromAlbum}")]
        public ActionResult ajoutPanier(int? id, int code, bool fromAlbum)
        {
            if (Session["Panier"] == null)
            {
                Session["Panier"] = new List<int>();
            }

            var items = (List<int>)Session["Panier"];

            bool present = false;

            foreach (var i in items)
            {
                if (i.Equals(id.Value))
                {
                    present = true;
                }
            }

            if (!present)
            {
                items.Add(id.Value);
            }



            Session["Panier"] = items;
            ViewBag.Panier = Session["Panier"];

            string chemin;

            if (fromAlbum)
            {
                chemin = "ListeEnregistrementsFromAlbum/" + code;
            }
            else
            {
                chemin = "ListeEnregistrementsFromOeuvres/" + code;
            }

            return RedirectToAction(chemin);
        }

        public ActionResult supprPanier(int? id, int code)
        {
            var items = (List<int>)Session["Panier"];

            if (Session["Panier"] != null)
            {
                if (items.Count() > 1)
                {
                    items.RemoveAt(items.Count());
                }
            }

            return null;
        }
    }
}

Projet/Controllers/MusiciensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projet;

namespace Projet.Controllers
{
    public class MusiciensController : Controller
    {
        private Classique_Web_2017Entities db = new Classique_Web_2017Entities();

        // GET: Musiciens
        public ActionResult Index()
        {
            var musicien = db.Musicien.Include(m => m.Genre).Include(m => m.Pays);
            return View(musicien.ToList());
        }
        public ActionResult Photo(int id)
        {
            var music = db.Musicien.Single(g => g.Code_Musicien == id);
            return File(music.Photo, "image/jpeg");
        }
        // GET: Musiciens/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Musicien musicien = db.Musicien.Find(id);
            if (musicien == null)
            {
                return HttpNotFound();
            }
            return View(musicien);
        }
        //GET: ListeCompositeurs
        public ActionResult ListeCompositeurs(string compo)
        {      
            
            if(compo == null)            
                compo = "";
              
            var musicien = (from m in db.Musicien
                            join comp in db.Composer
                            on m.Code_Musicien equals comp.Code_Musicien
                            where m.Nom_Musicien.StartsWith(compo)
                            select  m).Distinct();
            return View(musicien.ToList());
        }
        

   

    }
}

Projet/Views/Albums/Details.cshtml
@model Projet.Album

@{
    ViewBag.Title = "Details";
}

    <h2>Détails</h2>
    <h1>Album</h1>

<div>
    

    <dl class="dl-horizontal">
        <dt>
            Compositeur
        </dt>

        <dd>
            @ViewBag.Nom  @ViewBag.Prenom
        </dd>
        <dt>
            Titre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titre_Album)
        </dd>

        <dt>
            Année
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Annee_Album)
        </dd>

        <dd>
            <img src=@Url.Action("Pochette", "Albums", new { id = Html.DisplayFor(model => model.Code_Album)    }) width="350px" />
        </dd>

        <dt>
            Editeur
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Editeur.Nom_Editeur)
        </dd>

        <dt>
            Genre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.Libelle_Abrege)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Morceaux", "listeEnregistrementsFromAlbum", "Enregistrements", new { id = Model.Code_Album }, null) </br> 
    @Html.ActionLink("Oeuvres", "listeOeuvresFromAlbum", "Oeuvres", new { id = Model.Code_Album }, null) </br> 

</p>

Projet/Views/Albums/Index.cshtml
@model IEnumerable<Projet.Album>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titre_Album)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Annee_Album)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pochette)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ASIN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Editeur.Nom_Editeur)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre.Libelle_Abrege)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Titre_Album)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Annee_Album)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pochette)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ASIN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Editeur.Nom_Editeur)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre.Libelle_Abrege)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.Code_Album }) 
        </td>
    </tr>
}

</table>

Projet/Views/Albums/Photo.cshtml
@{
    ViewBag.Title = "Photo";
}

<h2>Photo</h2>

Projet/Views/Albums/listeAlbums.cshtml
@model IEnumerable<Projet.Album>
@{
    ViewBag.Title = "ListeAlbums";
}

<h2>Albums</h2>
<h1>@ViewBag.Nom  @ViewBag.Prenom</h1>
<p>
    @Html.ActionLink("Compositeur", "Details", "Musiciens", new { id = ViewBag.Code }, null) </br>
</p>

 <table class="table">


    <tr>
        <th>
            Titre
        </th>
        <th>
            Année
        </th>
        <th>
            Pochette
        </th>
    </tr>

    @foreach (var item in Model) 
    {
        <tr>
            <td>
                @Html.ActionLink((item.Titre_Album), "Details", new { id = item.Code_Album })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Annee_Album)
            </td>
            <td>
                <img src=@Url.Action("Pochette", "Albums", new { id = Html.DisplayFor(modelItem => item.Code_Album)   }) width="150px" />
            </td>
        </tr>
    }

</table>
   

Projet/Views/Albums/listeAlbumsFromOeuvres.cshtml
@model IEnumerable<Projet.Album>
@{
    ViewBag.Title = "Albums";
}


<h2>Enregistrements</h2>
<h1>@ViewBag.Titre_Album</h1>

<p>
    @Html.ActionLink("Album", "Details", "Albums", new { id = ViewBag.Code }, null) </br>
</p>

<table class="table">


    <tr>
        <th>
            Titre
        </th>
        <th>
            Année
        </th>
        <th>
            Pochette
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink((item.Titre_Album), "Details", new { id = item.Code_Album })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Annee_Album)
            </td>
            <td>
                <img src=@Url.Action("Pochette", "Albums", new { id = Html.DisplayFor(modelItem => item.Code_Album)   }) width="150px" />
            </td>
        </tr>
    }

</table>

Projet/Views/Albums/listeAlbumsRecherche.cshtml
@model IEnumerable<Projet.Album>
@{
    ViewBag.Title = "Albums";
}

<h2>Albums</h2>
@using (Html.BeginForm("ListeAlbumsRecherche", "Albums"))
{
    @Html.TextBox("alb")
    <input type="submit" value="Rechercher" />
}



<table class="table">
    <tr>
        <th>
            Titre
        </th>
        <th>
            Année
        </th>
        <th>
            @*Pochette*@
        </th>
    </tr>

    @foreach (var item in Model )
            {
        <tr>
            <td>
                @Html.ActionLink((item.Titre_Album), "Details", new { id = item.Code_Album })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Annee_Album)
            </td>
            <td>
                @*<img src=@Url.Action("Pochette", "Albums", new { id = Html.DisplayFor(modelItem => item.Code_Album)   }) width="150px" />*@
            </td>
        </tr>
    }

</table>

Projet/Views/Albums/listeEnregistrements.cshtml
@model IEnumerable<Projet.Enregistrement>
@{
    ViewBag.Title = "Enregistrements";
}

<h2>Enregistrements</h2>
<h1>@ViewBag.Titre_Album</h1>
<table class="table">


    <tr>
        <th>
            Titre
        </th>
        <th>
           Durée
        </th>
        <th>
            Extrait
        </th>
        <th>
            Prix
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Duree)
            </td>
            <td>
                <audio src=@Url.Action("Extrait", "Albums", new { id = Html.DisplayFor(modelItem => item.Code_Morceau)   }) controls />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prix) €
            </td>

        </tr>
    }

</table>