Projet/Controllers/MusiciensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projet;

namespace Projet.Controllers
{
    public class MusiciensController : Controller
    {
        private Classique_Web_2017Entities db = new Classique_Web_2017Entities();

        // GET: Musiciens
        public ActionResult Index()
        {
            var musicien = db.Musicien.Include(m => m.Genre).Include(m => m.Pays);
            return View(musicien.ToList());
        }
        public ActionResult Photo(int id)
        {
            var music = db.Musicien.Single(g => g.Code_Musicien == id);
            return File(music.Photo, "image/jpeg");
        }
        // GET: Musiciens/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Musicien musicien = db.Musicien.Find(id);
            if (musicien == null)
            {
                return HttpNotFound();
            }
            return View(musicien);
        }
        //GET: ListeCompositeurs
        public ActionResult ListeCompositeurs(string compo)
        {      
            
            if(compo == null)            
                compo = "";
              
            var musicien = (from m in db.Musicien
                            join comp in db.Composer
                            on m.Code_Musicien equals comp.Code_Musicien
                            where m.Nom_Musicien.StartsWith(compo)
                            select  m).Distinct();
            return View(musicien.ToList());
        }
        

   

    }
}

Projet/Controllers/OeuvresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projet;

namespace Projet.Controllers
{
    public class OeuvresController : Controller
    {
        private Classique_Web_2017Entities db = new Classique_Web_2017Entities();

        // GET: Oeuvres
        public ActionResult Index()
        {
            var oeuvre = db.Oeuvre.Include(o => o.Type_Morceaux);
            return View(oeuvre.ToList());
        }

        // GET: Oeuvres/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oeuvre oeuvre = db.Oeuvre.Find(id);
            if (oeuvre == null)
            {
                return HttpNotFound();
            }

            var data = (from o in db.Oeuvre
                         join comp in db.Composer on o.Code_Oeuvre equals comp.Code_Oeuvre
                         join mus in db.Musicien on comp.Code_Musicien equals mus.Code_Musicien
                         where o.Code_Oeuvre == id
                         select mus).Single();

            ViewBag.Nom = data.Nom_Musicien;
            ViewBag.Prenom = data.Prenom_Musicien;

            return View(oeuvre);
        }
        public ActionResult ListeOeuvresFromCompositeur(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            var oeuvre = (from o in db.Oeuvre
                          join comp in db.Composer on o.Code_Oeuvre equals comp.Code_Oeuvre
                          join mus in db.Musicien on comp.Code_Musicien equals mus.Code_Musicien
                          where mus.Code_Musicien == id
                          select o).Distinct();

            var data = db.Musicien.Single(g => g.Code_Musicien == id);
            ViewBag.Nom = data.Nom_Musicien;
            ViewBag.Prenom = data.Prenom_Musicien;
            ViewBag.Code = data.Code_Musicien;

            return View(oeuvre.ToList());
        }

        public ActionResult ListeOeuvresRecherche(string data)
        {
            if (data == null)
                data = "";

            var oeuvre = (from o in db.Oeuvre
                          join comp in db.Composer on o.Code_Oeuvre equals comp.Code_Oeuvre
                          join mus in db.Musicien on comp.Code_Musicien equals mus.Code_Musicien
                          where o.Titre_Oeuvre.StartsWith(data)
                          select o).Include(o => o.Type_Morceaux);
            return View(oeuvre.ToList());
        }

        public ActionResult ListeOeuvresFromAlbum(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var oeuvres = (from oe in db.Oeuvre
                                  join comp in db.Composer on oe.Code_Oeuvre equals comp.Code_Oeuvre
                                  join mus in db.Musicien on comp.Code_Musicien  equals mus.Code_Musicien
                                  join gen in db.Genre on mus.Code_Genre equals gen.Code_Genre
                                  join alb in db.Album on gen.Code_Genre equals alb.Code_Genre
                                  where alb.Code_Album == id
                                  select oe).Distinct();
            var data = db.Album.Single(g => g.Code_Album== id);
            ViewBag.Titre_Album = data.Titre_Album;
            ViewBag.Code = id;
            return View(oeuvres);
        }
    }

        

      
}

Projet/Views/Oeuvres/Details.cshtml
@model Projet.Oeuvre
@{
    ViewBag.Title = "Details";
}
<div>
    <h4>Oeuvre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Compositeur
        </dt>

        <dd>
            @ViewBag.Nom  @ViewBag.Prenom
        </dd>
        <dt>
            Titre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titre_Oeuvre)
        </dd>

        <dt>
            Sous Titre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sous_Titre)
        </dd>

        <dt>
            Tonalité
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tonalite)
        </dd>

        <dt>
            Année
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Annee)
        </dd>

        <dt>
            Opus
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opus)
        </dd>

        <dt>
            Numéro de l'opus
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Numéro_Opus)
        </dd>

        <dt>
            Type
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type_Morceaux.Libelle_Type)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "ListeOeuvresRecherche") </br>
    @Html.ActionLink("Enregistrements", "listeEnregistrementsFromOeuvres","Enregistrements", new { id = Model.Code_Oeuvre}, null) </br>
    @Html.ActionLink("Albums", "listeAlbumsFromOeuvres", "Albums", new { id = Model.Code_Oeuvre }, null)




</p>

Projet/Views/Oeuvres/Index.cshtml
@model IEnumerable<Projet.Oeuvre>

@{
}


    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titre_Oeuvre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sous_Titre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tonalite)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Annee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Opus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Numéro_Opus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type_Morceaux.Libelle_Type)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titre_Oeuvre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sous_Titre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tonalite)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Annee)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Opus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Numéro_Opus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type_Morceaux.Libelle_Type)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Code_Oeuvre }) |
                @Html.ActionLink("Details", "Details", new { id=item.Code_Oeuvre }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Code_Oeuvre })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

Projet/Views/Oeuvres/ListeOeuvres.cshtml
@model IEnumerable<Projet.Oeuvre>
@{
    ViewBag.Title = "ListeOeuvres";
}

<h2>Oeuvres</h2>
@using (Html.BeginForm("ListeOeuvres", "Oeuvres"))
{
    @Html.TextBox("data")
    <input type="submit" value="Rechercher" />
}

<table class="table">


    <tr>
        <th>
            Titre
        </th>

        <th>
            Type
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink((item.Titre_Oeuvre), "Details", new { id = item.Code_Oeuvre })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type_Morceaux.Libelle_Type)
            </td>
        </tr>
    }

</table>

Projet/Views/Oeuvres/ListeOeuvresFromCompositeur.cshtml
@model IEnumerable<Projet.Oeuvre>
@{
    ViewBag.Title = "ListeOeuvresFromCompositeur";
}

<h2>Oeuvres</h2>
<h1>@ViewBag.Nom  @ViewBag.Prenom</h1>
<p>
    @Html.ActionLink("Compositeur", "Details", "Musiciens", new { id = ViewBag.Code }, null) </br>
</p>

<table class="table">


    <tr>
        <th>
            Titre
        </th>

        <th>
            Type
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink((item.Titre_Oeuvre), "Details", new { id = item.Code_Oeuvre })
            </td>
            <td>
               @Html.DisplayFor(modelItem => item.Type_Morceaux.Libelle_Type)
            </td>
        </tr>
    }

</table>

Projet/Views/Oeuvres/ListeOeuvresRecherche.cshtml
@model IEnumerable<Projet.Oeuvre>
@{
    ViewBag.Title = "ListeOeuvresRecherche";
}

<h2>Oeuvres</h2>
@using (Html.BeginForm("ListeOeuvresRecherche", "Oeuvres"))
{
    @Html.TextBox("data")
    <input type="submit" value="Rechercher" />
}

<table class="table">


    <tr>    
        <th>
            Titre
        </th>

        <th>
            Type
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink((item.Titre_Oeuvre), "Details", new { id = item.Code_Oeuvre })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type_Morceaux.Libelle_Type)
            </td>
        </tr>
    }

</table>

Projet/Views/Oeuvres/listeOeuvresFromAlbum.cshtml
@model IEnumerable<Projet.Oeuvre>
@{
    ViewBag.Title = "Oeuvres";
}


<h2>Enregistrements</h2>
<h1>@ViewBag.Titre_Oeuvre</h1>

<p>
    @Html.ActionLink("Album", "Details", "Oeuvres", new { id = ViewBag.Code }, null) </br>
</p>

<table class="table">


    <tr>
        <th>
           Titre de l'Oeuvre
        </th>
        <th>
            Type de morceaux
        </th>
       
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titre_Oeuvre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type_Morceaux.Libelle_Type)
            </td>          
        

        </tr>
    }

</table>